import { Navbar } from '@/components/Navbar';
import './globals.css';
import { Footer } from '@/components/Footer';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				<main>{children}</main>
				<div id="modal-root"></div>
				<Footer />
			</body>
		</html>
	);
}
