import { Navbar } from '@/components/Navbar';
import './globals.css';
import { Footer } from '@/components/Footer';
import { DataProvider } from '@/components/DataProvider';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<DataProvider>
					<Navbar />
					<main>{children}</main>
					<Footer />
				</DataProvider>
				<div id="modal-root"></div>
			</body>
		</html>
	);
}
